# config/cnn_experiment.yml
experiment:
  name: "CNN_Text_Classification"
  version: "1.0"

mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_id: "0"
  run_name: "CNN_Simple_v1.0"
  tags:
    mlflow.runName: "CNN_Text_Classification"
    version: "1.0"
    model_type: "CNN"

data:
  source_run: "Second_dataset_experiment"
  artifact_path: "data/Dataset_2.csv"
  
  # Колонки
  text_column: "span"
  label_column: "label"

preprocessing:
  vocab_size: 5000
  max_length: 50
  padding: "post"
  clean_nan: true

model:
  embedding_dim: 64
  conv_filters: 64
  conv_kernel_size: 3
  dense_units: 64
  dropout_rate: 0.3
  
  optimizer: "adam"
  loss: "sparse_categorical_crossentropy"
  metrics: ["accuracy"]

training:
  test_size: 0.2
  random_state: 42
  validation_split: 0.1
  epochs: 5
  batch_size: 64
  
  early_stopping:
    monitor: "val_accuracy"
    patience: 2
    restore_best_weights: true

visualization:
  plot_history: true
  plot_confusion: true

class_names:
  0: "neutral"
  1: "joy"
  2: "sadness"
  3: "anger"
  4: "fear"
  5: "surprise"